In [1]:
import pandas as pd
import numpy as np

In [2]:
np.random.seed(101)
scores = np.random.randint(0,101, (4,3)) # 4 player 3 match
print(scores)

[[95 11 81]
 [70 63 87]
 [75  9 77]
 [40  4 63]]


In [16]:
players = ['Virat', 'MS Dhoni', 'KL Rahul', 'Rohit']
matches = ['Match 1', 'Match 2', 'Match 3']

In [17]:
df = pd.DataFrame(data=scores)

In [18]:
df

0   1   2
0  95  11  81
1  70  63  87
2  75   9  77
3  40   4  63

In [19]:
df = pd.DataFrame(data=scores)
df

0   1   2
0  95  11  81
1  70  63  87
2  75   9  77
3  40   4  63

In [21]:
df = pd.DataFrame(data=scores, index=players, columns=matches)
df

Match 1  Match 2  Match 3
Virat          95       11       81
MS Dhoni       70       63       87
KL Rahul       75        9       77
Rohit          40        4       63

In [22]:
df.loc['Virat']

Match 1    95
Match 2    11
Match 3    81
Name: Virat, dtype: int32

In [23]:
df.loc[['Virat', 'Rohit']]

Match 1  Match 2  Match 3
Virat       95       11       81
Rohit       40        4       63

In [26]:
print(df.loc['Virat', 'Match 2'])

11
